---
- hosts: localhost
  tasks:
  - name: Store public ssh key
    shell: cat keys/id_rsa.pub
    register: public_key
  - name: Store private ssh key
    shell: cat keys/id_rsa
    register: private_key
  - name: Store public ssh key in digital ocean
    digital_ocean:
      state: present
      command: ssh
      name: ansible_ssh_key
      ssh_pub_key: "{{ public_key.stdout }}"
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes
    register: my_key
  - name: Create droplet
    digital_ocean:
        state: present
        command: droplet
        name: host0
        api_token: "{{ digital_ocean_api_token }}"
        size_id: 512mb
        region_id: tor1
        image_id: ubuntu-16-04-x64
        unique_name: yes
        ssh_key_ids: "{{ my_key.ssh_key.id }}"
    register: host0
  - add_host: 
      name: "{{ host0.droplet.ip_address }}"
      groups: host0
      ansible_ssh_private_key_file: keys/id_rsa
  - pause: seconds=20

- hosts: host0
  strategy: free
  remote_user: root
  gather_facts: no
  tasks:
  - name: Install python2
    raw: apt-get -y install python-minimal

- hosts: host0
  remote_user: root
  tasks:
  - name: Install nginx
    apt: 
      name: nginx
      state: present
  - name: Update nginx.conf
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Create /home/static directory
    file:
      path: /home/static
      state: directory
  - name: Copy index.html
    copy:
      src: files/index.html
      dest: /home/static/index.html
  - name: Restart nginx service
    service:
      name: nginx
      state: restarted
