---
# file: simple-playbook.yml

- hosts: node_exporter_servers
  become: True
  roles:
    - williamyeh.prometheus
  vars:
    prometheus_components: [ "node_exporter" ]
    prometheus_node_exporter_version: 0.12.0
    prometheus_node_exporter_opts: -auth.pass='{{ node_exporter_password }}'' -auth.user='{{ node_exporter_user }}''

- hosts: prometheus_server
  become: True
  roles:
  	- williamyeh.prometheus
  vars:
  	prometheus_components: [ "prometheus" ]
  	prometheus_version: 0.20.0
  	prometheus_conf_main: files/prometheus.j2